# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23a3f431f206de006d058805d2d6615975752970bd9f29dab331a904c4fe53e7afab31a09f5758baf635740f8218fc761130780b7434a82688561fedb47d2667

test:
  secret_key_base: 587a0e3ec9d5170ff7139d43b6c4bb4145c6169cb989b8fe12621cfdaab3a1d79ea1b5827c005aef5db75ad1ef7738bfa035fcd74374e25d467524c5789f7654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
